//  Alerts.swift
//  StroybazaDeliveryApp
//  Created by Анастасия Набатова on 1/11/23.

import Foundation

enum AlertMessage {
    static let emptyMessage = ""
    static let promoTitle = "Введите ваш промокод"
    static let promoPlaceholder = "Промокод"
    static let promoKey = "attributedTitle"
    static let closelAction = "Закрыть"
    static let applyAction = "Применить"
    static let promoResult = "Результат"
    static let okAction = "OK"
    static let yesAction = "Да"
    static let noAction = "Нет"
    static let promoCode10 = "Promo 10"
    static let promoCode20 = "Promo 20"
    static let promoCode30 = "Promo 30"
    static let promoDiscount10 = "Будет применена скидка 10%"
    static let promoDiscount20 = "Будет применена скидка 20%"
    static let promoDiscount30 = "Будет применена скидка 30%"
    static let discountMessage = "Промо кода не существует"
    static let createProduct = "Данные сохранены"
    static let createProductMessage = "Ваши данные были успешно обновлены."
    static let createProductWarning = "Внимание"
    static let createProductWarningMessage = "Не все поля заполнены."
    static let createProductWarningContinue = "Продолжить"
    static let createProductWarningBack = "Меню"
    static let updateProductTitle = "Данные изменены"
    static let updateProductMessage = "Ваши данные были успешно обновлены."
    static let deleteProductTitle = "Данные изменены"
    static let deleteProductMessage = "Вы уверены, что хотите удалить этот продукт?"
    static let imageTitle = "Добавить изображение"
    static let galeryAction = "Галерея"
    static let photoAction = "Сделать фото"
    static let cancelAction = "Отмена"
    static let errorTitle = "Ошибка"
    static let errorMessage = "Произошла ошибка при сохранении товара."
    static let exitTitle = "Хотите выйти?"
    static let authMessage = "Заполните все поля"
    static let authError = "Ошибка авторизации:"
    static let authFields = "Заполните все поля"
    static let authPassword = "Пароли не совпадают"
    static let authErrorRegist = "Ошибка регистрации:"
    static let orderStatus = "Выберите статус заказа"   
    static let deleteAccount = "Удалить аккаунт"
    static let deleteQuestion = "Вы уверены, что хотите удалить свою учетную запись?"
    static let deleteAction = "Удалить"
    static let deleteTitle = "Аккаунт удален"
    static let deleteMessage = "Ваш аккаунт успешно удален."
}
